parameters:
  archType: ''
  buildConfig: ''
  condition: true
  container: ''
  crossBuild: false
  dependOnEvaluatePaths: false
  disableComponentGovernance: false
  isOfficialBuild: false
  osGroup: ''
  osSubgroup: ''
  platform: ''
  pool: ''
  runtimeVariant: ''
  testGroup: ''
  timeoutInMinutes: ''
  variables: {}

### Product build
jobs:
- template: xplat-pipeline-job.yml
  parameters:
    buildConfig: ${{ parameters.buildConfig }}
    archType: ${{ parameters.archType }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    runtimeVariant: ${{ parameters.runtimeVariant }}
    testGroup: ${{ parameters.testGroup }}
    helixType: 'build/product/'
    pool: ${{ parameters.pool }}
    condition: ${{ parameters.condition }}
    dependOnEvaluatePaths: ${{ parameters.dependOnEvaluatePaths }}
    disableComponentGovernance: ${{ parameters.disableComponentGovernance }}

    # Compute job name from template parameters
    name: ${{ format('coreclr_{0}_product_build_{1}{2}_{3}_{4}',
      parameters.runtimeVariant,
      parameters.osGroup,
      parameters.osSubgroup,
      parameters.archType,
      parameters.buildConfig) }}
    displayName: ${{ format('CoreCLR {0} Product Build {1}{2} {3} {4}',
      parameters.runtimeVariant, parameters.osGroup, parameters.osSubgroup,
      parameters.archType,
      parameters.buildConfig) }}

    # Run all steps in the container.
    # Note that the containers are defined in platform-matrix.yml
    container: ${{ parameters.container }}

    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}

    crossBuild: ${{ parameters.crossBuild }}

    gatherAssetManifests: true
    variables:
    - name: osGroup
      value: ${{ parameters.osGroup }}
    - name: osSubgroup
      value: ${{ parameters.osSubgroup }}
    - name: publishLogsArtifactPrefix
      value: 'BuildLogs_CoreCLR'
    - name: officialBuildIdArg
      value: ''
    - ${{ if eq(parameters.isOfficialBuild, true) }}:
      - name: officialBuildIdArg
        value: '/p:OfficialBuildId=$(Build.BuildNumber)'
    - name: enforcePgoArg
      value: ''
    # The EnforcePGO script is only supported on Windows and is not supported on arm64.
    - ${{ if and(eq(parameters.buildConfig, 'Release'), and(eq(parameters.osGroup, 'windows'), ne(parameters.archType, 'arm64'))) }}:
      - name: enforcePgoArg
        value: '-enforcepgo'

    - name: clrRuntimeComponentsBuildArg
      value: ''
    - ${{ if ne(parameters.testGroup, 'innerloop') }}:
      - name: clrRuntimeComponentsBuildArg
        value: '-component runtime -component alljits -component nativeaot -component spmi '

    # Set a default empty argument for the pgo path.
    # This will be set during the 'native prerequisites' step if PGO optimization is enabled.
    - name: CoreClrPgoDataArg
      value: ''

    - name: nativeSymbols
      value: ''
    - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: nativeSymbols
        value: '--keepnativesymbols'

    - ${{ parameters.variables }}

    steps:
    # Install native dependencies
    # Linux builds use docker images with dependencies preinstalled,
    # and FreeBSD builds use a build agent with dependencies
    # preinstalled, so we only need this step for OSX and Windows.
    - ${{ if in(parameters.osGroup, 'osx', 'maccatalyst', 'ios', 'iossimulator', 'tvos', 'tvossimulator') }}:
      - script: $(Build.SourcesDirectory)/eng/install-native-dependencies.sh $(osGroup)
        displayName: Install native dependencies

    # Install internal tools on official builds
    # Since our internal tools are behind an authenticated feed,
    # we need to use the DotNetCli AzDO task to restore from the feed using a service connection.
    # We can't do this from within the build, so we need to do this as a separate step.
    - ${{ if and(eq(variables['System.TeamProject'], 'internal'), ne(variables['Build.Reason'], 'PullRequest')) }}:
      - template: /eng/pipelines/common/restore-internal-tools.yml

    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - ${{ if ne(parameters.osGroup, 'windows') }}:
        - task: Bash@3
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.sh
            arguments: $(Build.SourcesDirectory)/NuGet.config $Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)
      - ${{ if eq(parameters.osGroup, 'windows') }}:
        - task: PowerShell@2
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
            arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)

    - ${{ if in(parameters.osGroup, 'osx', 'ios', 'tvos') }}:
      - script: |
          du -sh $(Build.SourcesDirectory)/*
          df -h
        displayName: Disk Usage before Build

    # Build/Generate native prerequisites
    - script: $(Build.SourcesDirectory)$(dir)build$(scriptExt) -subset clr.nativeprereqs $(crossArg) -arch $(archType) -c $(buildConfig) $(officialBuildIdArg) -ci /bl:$(Build.SourcesDirectory)artifacts/log/$(buildConfig)/CoreCLRNativePrereqs.binlog
      displayName: Build and generate native prerequisites

    # Build CoreCLR Runtime
    - ${{ if ne(parameters.osGroup, 'windows') }}:
      - script: $(Build.SourcesDirectory)/src/coreclr/build-runtime$(scriptExt) $(buildConfig) $(archType) $(crossArg) -ci $(clrRuntimeComponentsBuildArg) $(officialBuildIdArg) $(CoreClrPgoDataArg) $(nativeSymbols)
        displayName: Build CoreCLR Runtime
    - ${{ if eq(parameters.osGroup, 'windows') }}:
      - script: $(Build.SourcesDirectory)/src/coreclr/build-runtime$(scriptExt) $(buildConfig) $(archType) -ci $(enforcePgoArg) $(officialBuildIdArg) $(CoreClrPgoDataArg)
        displayName: Build CoreCLR Runtime

    - ${{ if or(eq(parameters.crossBuild, 'true'), ne(parameters.archType, 'x64')) }}:
      - script: $(Build.SourcesDirectory)/src/coreclr/build-runtime$(scriptExt) $(buildConfig) $(archType) -hostarch x64 -ci -component crosscomponents -cmakeargs "-DCLR_CROSS_COMPONENTS_BUILD=1" $(officialBuildIdArg)
        displayName: Build CoreCLR Cross-Arch Tools (Tools that run on x64 targeting x86)

    - ${{ if in(parameters.osGroup, 'osx', 'ios', 'tvos') }}:
      - script: |
          du -sh $(Build.SourcesDirectory)/*
          df -h
        displayName: Disk Usage after Build

    # Build CoreCLR Managed Components
    - script: $(Build.SourcesDirectory)$(dir)build$(scriptExt) -subset clr.corelib+clr.nativecorelib+clr.nativeaotlibs+clr.tools+clr.packages $(crossArg) -arch $(archType) -c $(buildConfig) $(officialBuildIdArg) -ci
      displayName: Build managed product components and packages

    # Publish product output directory for consumption by tests.
    - template: /eng/pipelines/common/upload-artifact-step.yml
      parameters:
        rootFolder: $(buildProductRootFolderPath)
        includeRootFolder: false
        archiveType: $(archiveType)
        tarCompression: $(tarCompression)
        archiveExtension: $(archiveExtension)
        artifactName: $(buildProductArtifactName)
        displayName: 'product build'

    - ${{ if and(eq(parameters.isOfficialBuild, true), eq(parameters.osGroup, 'windows')) }}:
      - powershell: ./eng/collect_vsinfo.ps1 -ArchiveRunName postbuild_log
        displayName: Collect vslogs on exit
        condition: always()

    # Publish Logs
    - task: PublishPipelineArtifact@1
      displayName: Publish Logs
      inputs:
        targetPath: $(Build.SourcesDirectory)/artifacts/log
        artifactName: '$(publishLogsArtifactPrefix)_Attempt$(System.JobAttempt)_$(osGroup)$(osSubgroup)_$(archType)_$(buildConfig)'
      continueOnError: true
      condition: always()
