parameters:
  buildConfig: ''
  archType: ''
  osGroup: ''
  osSubgroup: ''
  name: ''
  helixType: '(unspecified)'
  container: ''
  testGroup: ''
  crossBuild: false
  liveLibrariesBuildConfig: ''
  strategy: ''
  pool: ''

  # arcade-specific parameters
  condition: true
  continueOnError: false
  dependsOn: ''
  dependOnEvaluatePaths: false
  displayName: ''
  timeoutInMinutes: ''
  enableMicrobuild: ''
  gatherAssetManifests: false
  disableComponentGovernance: false

  variables: {} ## any extra variables to add to the defaults defined below

jobs:
- template: /eng/pipelines/common/templates/runtimes/xplat-job.yml
  parameters:
    buildConfig: ${{ parameters.buildConfig }}
    archType: ${{ parameters.archType }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    name: ${{ parameters.name }}
    helixType: ${{ parameters.helixType }}
    container: ${{ parameters.container }}
    crossBuild: ${{ parameters.crossBuild }}
    strategy: ${{ parameters.strategy }}
    pool: ${{ parameters.pool }}

    # arcade-specific parameters
    condition: and(succeeded(), ${{ parameters.condition }})
    continueOnError: ${{ parameters.continueOnError }}
    dependsOn: ${{ parameters.dependsOn }}
    dependOnEvaluatePaths: ${{ parameters.dependOnEvaluatePaths }}
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    enableMicrobuild: ${{ parameters.enableMicrobuild }}
    gatherAssetManifests: ${{ parameters.gatherAssetManifests }}
    disableComponentGovernance: ${{ parameters.disableComponentGovernance }}

    variables:
    - template: /eng/pipelines/common/templates/runtimes/native-test-assets-variables.yml
      parameters:
        runtimeFlavor: coreclr
        liveLibrariesBuildConfig: ${{ parameters.liveLibrariesBuildConfig }}

    - name: priorityArg
      value: ''

    # 'innerloop' and 'clrinterpreter' jobs run the Priority 0 tests; everything else runs the Priority 1 tests.
    # 'gc-standalone' is forced to run pri0 as well to start with.
    - ${{ if and(ne(parameters.testGroup, 'innerloop'), ne(parameters.testGroup, 'clrinterpreter'), ne(parameters.testGroup, 'gc-standalone'), ne(parameters.testGroup, 'gc-standalone-server') ) }}:
      - ${{ if ne(parameters.osGroup, 'windows') }}:
        - name: priorityArg
          value: 'priority1'
      - ${{ if eq(parameters.osGroup, 'windows') }}:
        - name: priorityArg
          value: '-priority 1'

    - ${{ each variable in parameters.variables }}:
      - ${{insert}}: ${{ variable }}

    steps: ${{ parameters.steps }}
